jobs:
- job:
  displayName: Win
  pool:
    vmImage: "windows-2019"
  strategy:
    matrix:
      Python37:
        CONDA_PY: '3.7'
        CONDA_NPY: '1.18'
      Python39:
        CONDA_PY: '3.9'
        CONDA_NPY: '1.19'

  steps:
  - template: checkout.yml
  - task: BatchScript@1
    inputs:
      filename: "$(CONDA)\\Scripts\\activate.bat"
      modifyEnvironment: True
    displayName: Add conda to PATH
  - template: conda-setup+build.yml
  - template: test-results.yml
